name: Build and Release to GitHub

on:
  push:
    branches:
      - main

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    defaults:
      run:
        working-directory: packages/lib

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 10

      - name: Install dependencies
        run: pnpm install --frozen-lockfile
        working-directory: .

      - name: Build UMD
        run: pnpm build

      - name: Get version
        id: pkg
        run: echo "VERSION=$(node -p 'require(\"./packages/my-lib/package.json\").version')" >> $GITHUB_OUTPUT

      - name: Create Git tag
        run: |
          git tag adv-wrapper-v${{ steps.pkg.outputs.VERSION }}
          git push origin adv-wrapper-v${{ steps.pkg.outputs.VERSION }}

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: adv-wrapper-lib${{ steps.pkg.outputs.VERSION }}
          files: packages/lib/dist/**
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
