name: Build and Release UMD ima3 CTV

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 10

      - name: Install dependencies
        run: pnpm install

      - name: Build UMD
        run: |
          cd packages/lib
          pnpm install
          pnpm build

      - name: Get version from package.json
        id: get_version
        run: |
          VERSION=$(node -p "require('./packages/lib/package.json').version")
          MAJOR=$(echo "$VERSION" | cut -d. -f1)
          echo "VERSION=v$VERSION" >> $GITHUB_ENV
          echo "MAJOR=v$MAJOR" >> $GITHUB_ENV

      - name: Create GitHub Release with Auto Changelog
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          files: |
            packages/lib/dist/*.js
          tag_name: ${{ env.VERSION }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Move dist files to a versioned folder
        run: |
          mkdir -p packages/lib/dist/${{ env.MAJOR }}
          find packages/lib/dist -maxdepth 1 -type f -exec mv {} packages/lib/dist/${{ env.MAJOR }}/ \;

      - name: Copy versioned files to latest folder
        run: |
          mkdir -p packages/lib/dist/latest
          cp -r packages/lib/dist/${{ env.VERSION }}/* packages/lib/dist/latest/

      - name: Deploy dist/ to gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: packages/lib/dist
          publish_branch: gh-pages
          user_name: github-actions[bot]
          user_email: github-actions[bot]@users.noreply.github.com
