name: Build and Release UMD ima3 CTV

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 10

      - name: Install dependencies
        run: pnpm install

      - name: Build UMD
        run: |
          cd packages/lib
          pnpm install
          pnpm build
          echo "VERSION=v$(node -p \"require('./package.json').version\")" >> $GITHUB_ENV

      - name: Create GitHub Release with Auto Changelog
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true # ✨ auto "What's new" based on commits
          files: |
            packages/lib/dist/*.js
          tag_name: ${{ env.VERSION }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
